%let dsname=carsMod3;

%macro simplePrint;
	data &dsname;
		set sashelp.cars;

		if mod(_N_, 3)=0;
		cars_city_range=put(mpg_city, range.);
	run;

	proc sort data=&dsname;
		by make cars_city_range;
	run;

	proc print data=&dsname(obs=10);
		by make;
	run;

%mend;

%simplePrint

/* global macro variable dsname is available to the macro as well */

/* notice how there is not a lot of info printed in the log */

/* turn on debugging options and rerun the macro */
/*Macro debugging options*/
/*most commonly used*/
options mprint mlogic symbolgen;
/*mprint - prints the sas code generated by the macro in the log*/
/*mlogic - prints the macro logic in conditional macro statements and %do loops*/
/*symbolgen - prints the value of the variable in the log when it is resolved.*/

%simplePrint



options mprintnest mlogicnest;
/*same as mprint and mlogic for nested macro calls*/
/*mprint and mlogic only work on inner most macros*/

